BerkeleyLab/fiats

test/asymmetric_engine_test_m.f90
test/inference_engine_test_m.f90
test/main.f90

This PR adds a unit test based on a neural network that behaves asymmetrically with regard to its two inputs.  The default `dot_product`-based neural network passes the new test.   The test exposes one failure in the `matmul`-based neural network that will be demonstrated in a second PR.

Asymmetric network test

---

src/matmul_s.f90
test/asymmetric_engine_test_m.f90
test/inference_engine_test_m.f90

This PR adds four unit tests of `matmul`-based inference, exposing one test failure that is fixed by commit 30639f8.

Asymmetric-network test of matmul-based inference

---

example/concurrent-inference.f90
example/construct-and-write.f90
example/read-and-query.f90
scripts/run-fpm.sh-header
setup.sh

With this PR, the following works:
```
./setup.sh
./build/run-fpm.sh run \
--example <example-name> \
-- --input-file <network-file-name>
```
Previously, example-program arguments such as in the final line above weren't handled properly by `run-fpm.sh`.

Fix handling of example-program input arguments in run-fpm.sh script

---

example/read-and-infer.f90
src/inference_engine_m.f90
src/inference_engine_s.f90

Testing showed matmul to provide more accurate inference results matching the result of PyTorch to every significant digit.

Make matmul the default Inference strategy

---

test/asymmetric_engine_test_m.f90

What is Changing
------------------
This PR adds unit tests for the following `inference_engine_t` type-bound procedures:
* `num_inputs()`
* `num_outputs()`
* `neurons_per_layer()`
* `num_hidden_layers()`
Why It is Changing
-------------------
Having more fine-grained unit tests lays the groundwork for an upcoming refactoring that will eliminate the need for the `transpose()` invocations inside the `inference_engine_t` `infer` type-bound procedure.   The plan is to store weights in a transposed format upon construction of an `inference_engine_t` object, which will eliminate unnecessary subsequent computation inside the most performance-critical part Inference-Engine.  Changing the principal data structure in Inference-Engine will have pervasive impact.  The new unit tests will provide …

More comprehensive unit testing

---

src/inference_engine_m.f90
src/inference_engine_s.f90
test/inference_engine_test_m.f90

This PR enforces inference_engine_t internal self-consistency pre- and/or postconditions in every `inference_engine_t` type-bound procedure by calling the type-bound `assert_consistent()` subroutine.  Once this PR is merged, it should not be possible for any procedure to receive an `inference_engine_t` dummy argument that is internally inconsistent or to produce an `inference_engine_t` result that is internally inconsistent.

Enforce invariant `inference_engine_t` self-consistency

---

src/concurrent_dot_products_m.f90
src/concurrent_dot_products_s.f90
src/concurrent_dot_products_with_skip_m.f90
src/concurrent_dot_products_with_skip_s.f90
src/inference_engine_s.f90
src/inference_strategy_m.f90
src/matmul_m.f90
src/matmul_s.f90
src/matmul_with_skip_m.f90
src/matmul_with_skip_s.f90

This PR refactors the `inference_engine_t` user-defined constructor functions to store the `input_weights_` and `hidden_weights_` components in a form that is transposed relative to the corresponding constructor dummy arguments. Transposing the weights arrays inside the the constructors keeps the procedure interfaces the same but eliminates the need for transposition each time the `matmul` intrinsic is called during inference (once per layer), thus saving computation.

Transpose weights in the constructors

---

test/asymmetric_engine_test_m.f90
test/inference_engine_test_m.f90

Because a previous commit switched the default inference strategy to `matmul_t()` but `concurrent_dot_product_t()` was never specified explicitly in any tests, the latter strategy wasn't being tested. This commit fixes that so both strategies are tested explicitly and improves the test output.

Restore test coverage

---

test/main.f90
test/skip_connections_test_m.f90

This PR adds tests defining a two-input, one-output neural network with skip connections.  The network represents digital logic yielding true if and only if the 1st input is true but the 2nd input is false. The new tests check the entire truth table for the `matmul_with_skip_t()` and `concurrent_dot_products_with_skip_t()` inference strategies.

Add unit tests for networks with skip connections

---

src/inference_engine_m.f90
src/inference_engine_s.f90

This PR adds the capability to read a `metadata` JSON object if it is present before the `hidden_layers` array and formatted as follows:
```
"metadata": {
"modelName": "Network",
"modelAuthor": "Joe Bloggs",
"compilationDate": "2023-02-09 16:10:18.544724",
"usingSkipConnections": false
},
```
The corresponding information is used to construct a `metadata_t` object that is a new component in the `inference_engine_t` derive type.  If no `metadata` JSON object is found, then the `metadata_t` component is constructed with empty strings  and a `.false.`. The primary purpose of the new metadata object is to specify whether skip connections will be used between hidden layers.

Feature: read metadata if present

---

test/inference_engine_test_m.f90

This PR refactors the test of the `elemental` inference type- bound procedure, employing derived-type, dummy-argument array input to produce a derived-type array output result.

More stringent unit test for elemental inference

---

fpm.toml

This commit switches to using a version of the netcdf-interfaces dependency that has been patched to allow the use of implicit external interfaces.

fix(netcdf-interfaces): patch for fpm v >= 0.8

---

README.md
example/train-xor-gate.f90
setup.sh
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.f90
src/inference_engine/mini_batch_m.f90
src/inference_engine/mini_batch_s.f90
src/inference_engine/network_increment_m.f90
src/inference_engine/network_increment_s.f90
src/inference_engine/trainable_engine_m.f90
src/inference_engine/trainable_engine_s.f90
src/inference_engine_m.f90
test/main.f90
test/trainable_engine_test_m.f90

Group input/output pairs into mini-batches

---

app/train-cloud-microphysics.f90
example/train-and-write.f90
fpm.toml
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.f90
src/inference_engine/trainable_engine_m.f90
src/inference_engine/trainable_engine_s.f90
test/inference_engine_test_m.f90

1. refac(app): mv most of main to a subroutine
2. feat(app): train in user-specified time step range
3. feat(app): checkpoint restart from network file
4. feat(example): shorter compilation time 
5. chore(test): rm commented code
6. fix(trainable_engine_s): use single-precision

New app features & refactoring: checkpoint/restart and user-specified training time range

---

app/train-cloud-microphysics.f90

This pull request edits or adds command-line arguments of the form
--base <string> --stride <integer> --epochs <integer>
where stride --base was previously --base-name, --stride is the step interval between time instances that will be used for training, and --epochs is the number of complete passes through the data set for the current run.

feat(app): train in strided epochs

---

app/train-cloud-microphysics.f90
example/print-network-properties.f90
src/inference_engine/trainable_engine_s.f90

This pull request exhibits nearly monotonic convergence as measured by the cost function decreasing 3 orders of magnitude in the first 120 epochs:
To reproduce this behavior, execute
```
./build/run-fpm.sh run -- --base training --epochs 120 --stride 720
```
with the present working directory containing the 29.7 GB training_input.nc and training_output.nc produced for the "Colorado benchmark simulation" using commit d7aa958 on the neural-net branch of https://github.com/berkeleylab/icar, which uses the simplest of ICAR's cloud microphysics models.  The Inference-Engine run uses
* A single time instant (as determined by the above stride),
* A 30% retention rate of grid points where time derivatives vanish,
* Zero initial weights and biases,
* A batch size equal to the entire time instant, …

Feature: 1st converging cloud microphysics model

---

src/inference_engine/input_output_pair_m.f90
src/inference_engine/input_output_pair_s.f90
src/inference_engine_m.f90
test/trainable_engine_test_m.f90

In this pull request, the `perturbed_identity_converges()` test function executes at four parameters' threshold values required for training to converge:
Parameter        | Description                                                                   | Threshold or Required
---------------|----------------------------------------------------|-------------------
num_ephochs  | # passes through the full data set                              | 148
num_bins         | # mini-batches into which the data set is divided     | 5
stochastic        | whether a subroutine shuffles the data each epoch | yes
adam                | whether the Adam optimizer is used                          | yes
For the tested data set of size `num_pairs=6`, decrementing `num_epochs` or `num_bins` or not using …

test(train):test near radius of non-convergence

---

example/fit-polynomials.f90
example/train-and-write.f90

This pull request adds `example/fit-polynomials.f90`, which trains a neural network to learn linear combinations of the inputs.  The neural network learns to map eight inputs, `x(1:8)`, to six outputs corresponding to `y(x) = [x(1), x(2) + x(3), x(4), x(5), 0.5*x(6) + 1.5*x(7), x(8)]`, where the network uses 
* The ReLU activation function,
* An initial condition corresponding to a randomly perturbed identity mapping of the six inputs `x(2:7)`, i.e. `y(x) = [x(2), x(3), x(4), x(5), x(6), x(7)`,
* Two hidden layers with 8 nodes each.

Train linear combinations of inputs

---

.github/workflows/deploy-docs.yml

`apt` was installing `ford` 6, which was failing.  Also, with this PR, we'll no longer treat `ford` warnings as errors.

fix(deploy-docs.yml) - use linuxbrew to install ford 7

---

src/inference_engine/trainable_engine_s.f90

This PR switches two `do` loops in the training algorithm to `do concurrent` constructs.  Inspection of the code indicates that there are no values defined in one iteration that are accessed in a subsequent iteration. This conclusion was also tested by temporarily changing the stride of each affected `do` loops from the default (`1`) to `-1` in order to reverse the order of the iterations.  With a stride of `-1`, all tests pass and `app/train-cloud-microphysics.f90` yields the same convergence behavior as with a stride of `1` when run as follows using a training data set from ICAR.
```
./build/run-fpm.sh run -- --base training --start 720 --epochs 40 
```

Exploit additional concurrency in the training algorithm

---

example/concurrent-inferences.f90
example/learn-addition.f90
example/learn-exponentiation.f90
example/learn-microphysics-procedures.f90
example/learn-multiplication.f90
example/learn-power-series.f90
example/learn-saturated-mixing-ratio.f90
example/train-and-write.f90
example/write-read-infer.f90
setup.sh
test/trainable_engine_test_m.f90

- Edit setup.sh script to compile with OpenMP support
- Work around a compiler bug that causes a test to crash when OpenMP is enabled
A future commit will use OpenMP for GPU offloading.

Enable OpenMP in setup script & work around related compiler bug

---

src/inference_engine/activation_strategy_m.f90

`gfortran` accepts the `module` keyword that has been removed in this PR, but `ifx` and `nagfor` do not. NOTE: removing the keyword causes other issues to occur with `ifx` and `nagfor`, but `gfortran` is still able to compile.

Remove module keyword from abstract interface

---

example/learn-addition.f90
example/learn-exponentiation.f90
example/learn-microphysics-procedures.f90
example/learn-multiplication.f90
example/learn-power-series.f90
example/learn-saturated-mixing-ratio.f90
example/train-and-write.f90
src/inference_engine/activation_strategy_m.f90
src/inference_engine/inference_engine_s.f90
src/inference_engine/relu_m.f90
src/inference_engine/sigmoid_m.f90
src/inference_engine/step_m.f90
src/inference_engine/swish_m.f90
src/inference_engine/trainable_engine_m.f90
src/inference_engine/trainable_engine_s.f90
src/inference_engine/training_configuration_m.f90
test/main.f90
test/trainable_engine_test_m.f90

Various bugfixes in the code that were identified when trying to compile with `nag`.

Bugfixes for nag

---

test/main.F90
test/trainable_engine_test_m.F90

This PR works around all compile-time issues identified when building with the `nagfor` compiler. This PR contains the first commit that enables the `nagfor` compiler to build all of inference-engine.  Because all tests still pass with `gfortran` 13.2.0, this PR is safe to merge.
* Passing:
- hyperparameters_test_m
- network_configuration_test_m
- training_configuration_test_m
* Failing:
- inference_engine_test_m
* Crashing:
- asymmetric_engine_test_m
- trainable_engine_test_m

Nagfor workaround

---

test/trainable_engine_test_m.f90

This commit takes advantage of the fix in nagfor Build 7151.

chore(test): rm nagfor compiler workaround

---

fpm.toml

Update the fpm manifest to use the Assert 1.6.0  and Sourcery 4.6.0 releases that now support building those dependencies with the Cray Compiler Environment (CCE) 17.0.0 Fortran compiler.

build(fpm.toml): increment dependency versions

---

cloud-microphysics/app/train-cloud-microphysics.f90
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90
src/inference_engine/tensor_range_m.f90
src/inference_engine/tensor_range_s.f90
src/inference_engine/trainable_engine_m.F90
src/inference_engine/trainable_engine_s.F90
test/tensor_range_test_m.f90

This PR facilitates storing the range of values encountered in the training data for purposes of
1. Preventing undesired extrapolation during inference and
2. Normalizing inputs and unnormalizing outputs during inference to match the practice used in training.
See the cloud-microphysics subdirectory for an example of mechanics and utility of training-data normalization to aid convergence.
**BREAKING CHANGE:** network files will now contain a tensor_range JSON objects for inputs followed by a tensor_range JSON object for outputs, each of which stores a string label ("inputs" for the first and "outputs" for the second) followed by "minima" arrays and "maxima" arrays.

Feature: Add input/output tensor component ranges to network files

---

cloud-microphysics/app/train-cloud-microphysics.f90
cloud-microphysics/fpm.toml
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90
src/inference_engine/tensor_range_s.f90
src/inference_engine/trainable_engine_s.F90

To Do: the same mapping is needed in trainable_engine_t's infer procedure.

Feature: map input to unit range & output tensors from unit range in inference_engine_t infer procedure

---

src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90

Breaking Change
-----------------
This commit replaces pull request #147's `inference_engine_t` `input_range` and `output_range` getters with tensor mapping functions that delegate the input and output tensor mappings to the corresponding `inference_engine_t` `input_range_` and `output_range_` components' own `map_to_training_range` and `map_from_training_range` type-bound functions.

Feature: redesigned functionality for mapping input and output tensors to and from training ranges

---

fpm.toml

This ensures that the latest changes in the Sourcery dependency can be built by the ifx compiler.

build: update to sourcery 4.8.1

---

src/inference_engine/inference_engine_s.F90
test/trainable_engine_test_m.F90

This PR works around issues that arise when the following build command is used to tell the `ifx` compiler to automatically offload `do concurrent` constructs to a GPU:
```
fpm test --compiler ifx --flag "-coarray -coarray-num-images=1 -fopenmp-target-do-concurrent -qopenmp -fopenmp-targets=spir64"
```
The workarounds are
1. further reduce iterations in `trainable_engine_test_m` so training converges with `ifx` without crashing
2. convert `do concurrent` with array statements to `do` loops

Work around ifx automatic-offloading bugs

---

.github/workflows/CI.yml
example/learn-addition.F90
example/learn-exponentiation.F90
example/learn-microphysics-procedures.F90
example/learn-multiplication.F90
example/learn-power-series.F90
example/learn-saturated-mixing-ratio.F90
example/train-and-write.F90
fpm.toml
setup.sh
test/trainable_engine_test_m.F90

This branch adds fixes to the branch `switch-to-julienne` that allow the project to compile and test successfully. Once this is merged into the `switch-to-julienne` branch, that branch can be reviewed as a PR and merged into main.
The main changes are adding bug workarounds for an associate-stmt bug that was reintroduced into `gfortran-14`

Add bug workarounds for gfortran-14 associate-stmt bug

---

src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90
src/inference_engine/trainable_engine_m.F90
test/main.F90

- Fix bug unveiled by LLVM flang by replacing `pure` with `impure` keyword in procedures with an assignment-stmt or a result that involves polymorphic allocatable components.
- Add macro for flang to avoid compiling a `sync-all-stmt`.

Support compilation with LLVM Flang

---

cloud-microphysics/app/tensor-statistics.f90
cloud-microphysics/app/train-cloud-microphysics.f90
cloud-microphysics/fpm.toml
cloud-microphysics/setup.sh
cloud-microphysics/src/histogram_m.f90
cloud-microphysics/src/histogram_s.f90
cloud-microphysics/test/netCDF_file_test_m.f90

Switching the rest of Inference-Engine from depending on Sourcery to depending on Julienne broke the building of the `fpm` project in the `cloud-microphysics/` subdirectory.  This PR
1. Switches `cloud-microphysics/` from Sourcery to Julienne,
2. Updates the GCC compilers in `setup.sh` from version 13 to the latest version: 14, and
3. Updates the Assert dependency from version 1.6.0 to the latest version: 1.7.0.
where item 1 fixes the aforementioned build problem.

Update cloud-microphysics compiler and dependencies

---

cloud-microphysics/app/tensor-statistics.f90
cloud-microphysics/src/histogram_m.f90
cloud-microphysics/src/histogram_s.f90

This pull request switches the `cloud-microphysics` `histogram_t` constructor to using a different algorithm when the number of bins exceeds a threshold of 80, above which the new algorithm out-performs the original algorithm.  The original algorithm used `do concurrent`, but required accessing the entire data once per bin. The new algorithm is inherently serial, but only accesses the data set once, keeping a running tally of the bin count.  In a future commit, the new algorithm will also use `do concurrent` with compilers that support Fortran 2023 `reduce` locality.

Feature: Faster histogram construction when the number of bins exceeds 80

---

example/read-query-infer.f90
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90
src/inference_engine/metadata_m.f90
src/inference_engine/metadata_s.f90
src/inference_engine/neuron_m.f90
src/inference_engine/neuron_s.f90
src/inference_engine/tensor_range_s.f90
src/inference_engine/trainable_engine_m.F90
src/inference_engine/trainable_engine_s.F90
src/inference_engine_m.f90
test/main.F90
test/metadata_test_m.F90
test/tensor_range_test_m.F90

With this pull request, executing
```
fpm run --example read-query-infer -- --input-file uneven.json
```
gives the desired result of producing outputs identically equal to the corresponding inputs on a network with varying hidden-layer widths such as the attached file [uneven.json.gz](https://github.com/user-attachments/files/16059628/uneven.json.gz) when uncompressed.  The new `example/read-and-query.f90` program generates random inputs.  An example execution of the above line produces the output
```
Project is up to date
Reading an inference_engine_t object from the same JSON file 'uneven.json'.
Querying the new inference_engine_t object for several properties:
Activation function: relu
Number of outputs:           2
Number of inputs:           2
Nodes per layer:           2           2 …
```

Read & perform inference on networks for which the hidden-layer width varies across layers

---

example/single-file/single-file-compile.sh

This PR contains a script that concatenates Julienne and its dependencies into a single file and then compile the file with flang-new.

build: add single-file compile script

---

cloud-microphysics/app/train-cloud-microphysics.f90

This PR
1. Ensures cost reporting in the 1st & last epochs.
2. Reduces the JSON network file writing to once per reporting period.

feat(cloud-micro): write 1st/last cost, fewer JSON

---

src/inference_engine/trainable_engine_s.F90

This PR lays the groundwork for parallelizing or offloading a significant part of the training algorithm to a GPU.

Concurrent loop through each mini-batch during training

---

example/learn-saturated-mixing-ratio.F90
fpm.toml
src/inference_engine/inference_engine_m_.f90
src/inference_engine/inference_engine_s.F90
src/inference_engine/input_output_pair_m.f90
src/inference_engine/input_output_pair_s.f90
src/inference_engine/layer_m.f90
src/inference_engine/layer_s.f90
src/inference_engine/mini_batch_m.f90
src/inference_engine/neuron_s.f90
src/inference_engine/tensor_range_m.f90

This PR eliminates all but two warnings generated by compiling the single-source-file version of Inference-Engine with the NAG compiler.  The two remaining warnings are the subject of a just-submitted compiler bug report.

Eliminate compiler warnings

---

src/inference_engine/gelu_s.f90
src/inference_engine/sigmoid_s.f90

This PR fixes several compile-time constants to ensure that the double-precision versions of the GELU and sigmoid activation functions use double-precision throughout their evaluations.

Fix GELU & sigmoid activation precision

---

README.md

This PR updates the `training_configuration.json` file to include the newly added `"tensor names"` object.

doc(README): "tensor names" in JSON configuration

---

README.md
src/fiats/neural_network_m.f90
src/fiats/neural_network_s.F90

The 0.15.0 build does not currently work with ifx due to a few compiler bugs. These bugs will hopefully be fixed in an upcoming 2025 release of ifx. However, Fiats also has a few bugs that prevent compilation on ifx, which this PR addresses. See the commit messages for each individual commit for more details.

Fixes for building with ifx

---

src/fiats/trainable_network_s.F90

This PR enables the NAG compiler to build the Fiats library (all the code in the `src` subdirectory) and does so without breaking support for other compilers so it's safe to merge if the tests pass.  Additional work is needed to build other parts of Fiats such as the `example` subdirectory.

fix(trainable_network): work around nagfor bug

---

demo/fpm.toml
demo/src/time_data_m.F90
demo/src/time_data_s.F90
demo/test/main.F90
demo/test/time_data_test_m.F90

This PR defines a new `time_data_t` type in the `demo/src` that can be used to import time step information written by the [Berkley Lab ICAR fork](https://go.lbl.gov/icar]'s neural-network branch.  The new derived type is equipped with a `from_icar_format` constructor function for this purpose and with `to_json` and `from_json` functions that can be used for better formatting of the data.  The type also includes time stamp information for each time step.

Feature: read/write/test ICAR time step data

---

example/concurrent-inferences.f90

This commit
1. Fixes a typo in the name of one of the optional arguments accepted by the concurrent-inferences example and
2. Provides more complete usage information if a user neglects to provide required arguments.

fix(example): better usage info and argument handling

---

example/learn-saturated-mixing-ratio.F90
src/fiats/trainable_network_m.f90
src/fiats/trainable_network_s.F90

This commit adds a `trainable_network_t` constructor that accepts the components derived types components directly rather than exposing the use of its `neural_network_t` parent as an intermediary.  This eliminates the need for the `neural_network_t` type in the `learn-saturated-mixing-ratio example` and thereby makes that example's use of Fiats entities a subset of the entities used by the similar but much more complicated demonstration application `train-cloud-microphysics`.  This change makes the example a useful proxy for the demonstration application when introducing new users to the demonstration application in the ISS conference paper.

refac(example):simple learn-saturated-mixing-ratio

---

example/concurrent-inferences.f90

With this commit, the concurrent-inferences example prints the following usage information if the program doesn't receive the required command-line arguments:
```
Usage:
fpm run \
--example concurrent-inferences \
--compiler flang-new \
--flag -O3 \
-- --network "<file-name>" \
[--do-concurrent] [--openmp] [--elemental] [--double-precision] [--trials <integer>]
where <> indicates user input and [] indicates an optional argument.
```

chore(example): usage info specifies compiler

---

src/fiats/neural_network_m.f90

This commit makes `neural_network_t` generic "learn" binding private because it is intended to be called only by the `trainable_network_t` "train" procedure and the latter type is defined in the same module as the former.

chore(neural_network): make learn private

---

example/concurrent-inferences.f90

In `concurrent-inferences.f90`, this PR 
1. Removes an unused type from an `only` clause
2. Adds missing parentheses to a function declaration with an empty argument list.

Minor chore & fix

---

src/fiats/neural_network_m.f90

This PR fixes an issue that blocked building with the Intel `ifx` compiler.

Fix: make `learn` generic binding public

---

README.md

With this PR, the README.md file
1. Moves the NAG `nagfor` compiler back to the "Supported Compilers" section and
2. Condenses the LLVM `flang` and Intel `ifx` support text.

Update compiler support documentation

---

example/learn-addition.F90
example/learn-exponentiation.F90
example/learn-multiplication.F90
example/learn-power-series.F90
example/learn-saturated-mixing-ratio.F90
example/train-and-write.F90
src/fiats/layer_s.F90
src/fiats/neural_network_s.F90
src/fiats/neuron_s.F90
src/fiats/tensor_map_s.F90
test/asymmetric_network_test_m.F90
test/hyperparameters_test_m.F90
test/main.F90
test/metadata_test_m.F90
test/network_configuration_test_m.F90
test/neural_network_test_m.F90
test/tensor_map_test_m.F90
test/tensor_names_test.f90
test/tensor_test_m.f90
test/trainable_network_test_m.F90
test/training_configuration_test_m.F90
test/training_data_files_test_m.F90

This PR 
* Updates the dependencies to Julienne 2.4.3 and Assert 3.0.2.
* Replaces the Julienne 1.5.3 test feature, in which test functions produce a `logical` result, with the Julienne 2.4.3 feature, in which test functions produce a `test_diagnosis_t` object.
* Removes a `gfortran` workaround not needed with `gfortran` versions 14.3 or higher.

Update to Julienne 2.4.3 assert 3.0.2

---

README.md

Fix issue #273 
Added dependencies section to README with details on required tools and compilers.

Documentation: add dependencies section to README.md
